changelog:
  categories:
    - title: Enhancement
      labels:
        - Semver-Minor
        - enhancement
    - title: Bug fix
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
